CREATE TABLE "raw_transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "date" timestamp,
  "type" VARCHAR(10),
  "exchange" VARCHAR(50),
  "asset" VARCHAR(50),
  "price" DECIMAL(32, 18),
  "amount" DECIMAL(32, 18),
  "cost_basis" DECIMAL(32, 18),
  "fee" DECIMAL(32, 18)
);

CREATE TABLE "pairs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "tax_year" INT,
  "buy_transaction_id" INT,
  "buy_amount" DECIMAL(32, 18),
  "buy_cost_basis" DECIMAL(32, 18),
  "buy_fee" DECIMAL(32, 18),
  "sell_transaction_id" INT,
  "sell_amount" DECIMAL(32, 18),
  "sell_cost_basis" DECIMAL(32, 18),
  "sell_fee" DECIMAL(32, 18)
);

CREATE TABLE "tax_filings" (
  "year" INT PRIMARY KEY NOT NULL,
  "filed" boolean
);

COMMENT ON TABLE "raw_transactions" IS 'Transaction Data pulled from Exchange';

COMMENT ON TABLE "pairs" IS 'Raw buy amounts are split into multiple transactions to pair with sells';

ALTER TABLE "pairs" ADD FOREIGN KEY ("buy_transaction_id") REFERENCES "raw_transactions" ("id");

ALTER TABLE "pairs" ADD FOREIGN KEY ("sell_transaction_id") REFERENCES "raw_transactions" ("id");

ALTER TABLE "pairs" ADD FOREIGN KEY ("tax_year") REFERENCES "tax_filings" ("year");
